### ISSUE TITLE
[WebAPI] Test - SSO authorization

### ISSUE THREAD

**Issue by pawel-szczesny** [devonfw/mrchecker#111]
This should be an extension for web API part that will support SSO authorization.

For example -> establish a connection with http://nsc.capgemini.com/deliverykit/SSC/Podrecznik-Pracownika.aspx BUT  gmail SSO will be enough. However something lighter (and more stable) will be better (something like http.bin -> only hosting sso for test). I'm not sure if this is for it but I have found this page -> https://axiomsso.herokuapp.com/Home.action.

Example working solution code is in a separate repository: https://bitbucket.org/capntc/selenium_workshop/src/develop/src/main/java/com/example/webservice/service/

**Comment by pawel-szczesny** [comment]
@MalgorzataDzienia Description updated, please let me know if you have any other questions and concerns. You can do it via comments here.

**Comment by MalgorzataDzienia** [comment]
@pawel-szczesny : Do we have any technical user for accessing http://nsc.capgemini.com/deliverykit/SSC/Podrecznik-Pracownika.aspx ?

**Comment by MalgorzataDzienia** [comment]
@pawel-szczesny : As discussed today, please provide more details to this task.

**Comment by pawel-szczesny** [comment]
@MalgorzataDzienia : I have discussed it with Łukasz and gmail SSO will be enough. However something lighter (and more stable) will be better (something like http.bin -> only hosting sso for test). I'm not sure if this is for it but I have found this page -> https://axiomsso.herokuapp.com/Home.action.

**Comment by MalgorzataDzienia** [comment]
I did some analysis:
1. Our Capgemini acount cannot be used for open source tests.
2. Google mail usees non standard propertiary authorisation.
3. This page https://axiomsso.herokuapp.com/Home.action could work if I want do develop my own new sso Webpage and test it, but this is not the aim of this task. 
4. Mentioned working solution: https://bitbucket.org/capntc/selenium_workshop/src/develop/src/main/java/com/example/webservice/service/ has any test example, only library without any example of use.

This whole task is too vague defined. Please make it more precise or abandon it.

**Comment by MalgorzataDzienia** [comment]
@pawel-szczesny : Please confirm that my analysis is fine or reopen this task with new detailed description.
