### ISSUE TITLE
[Selenium] Upload file

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#142]
String absoulteCSVFilePath = FileImportHelper.getAbsoluteResorcesTestCSVImportFilePath(csvFileImport);
WebElement e = getDriver().findElementDynamic(selectorSuchenButton);
((RemoteWebElement) e).setFileDetector(new LocalFileDetector());
e.sendKeys(absoulteCSVFilePath);

Just not sure it is proper way 😉 I am sure you guys figures something out I just cannot find.

We ran into issue where our upload tests fail because grid nodes do not have access to Jenkins workspace. The failure message is:

Session ID: 330f9392-9121-4d77-ae7a-c416d6099868
  File not found: C:\Users\gstarcze\repos\saps\saps-under-
According to https://saucelabs.com/blog/selenium-tips-uploading-files-in-remote-webdriver the link between remote end and local file system can be achieved by putting this piece

webDriver.set(new RemoteWebDriver(new URL(remoteHubURL), caps));
                    ((RemoteWebDriver) webDriver.get()).setFileDetector(
                            new LocalFileDetector());

**Comment by gabrielstar** [comment]
I think one of my team initially raised this to MrChecker but we fixed it with sth like @lstefaniszyn you say.

`WebElement suchenButton = getDriver().findElementDynamic(selectorDifferenzleitdateiHochladenButton);
		if (getDriver().getClass()
				.getSimpleName()
				.equals("NewRemoteWebDriver")) {
			try {
				((RemoteWebElement) suchenButton).setFileDetector(new LocalFileDetector());
			} catch (Exception e) {
				BFLogger.logDebug("Error setting localFileDetector for Grid tests");
			}
		}
		suchenButton.sendKeys(filepath);`

That is probably because we already used boilerplate and could not change it at Driver level.
I will take it.
