### ISSUE TITLE
[Selenium] Allow re-sizing the browser window to a custom resolution

### ISSUE THREAD

**Issue by magdalenaBartkowiakJowsa** [devonfw/mrchecker#170]
Zglaszajacy:
Osada, Rafal rafal.osada@capgemini.com
Oles, Szymon szymon.oles@capgemini.com
Rygal, Janusz janusz.rygal@capgemini.com

skontaktowałam się z wymienionymi osobami w celu dościślenia zadania. Oto co sie dowiedziałam:

"Pamietam ze sporym problemem bylo dla nas to ze nawet jak ustalalismy swoja rozdzielczosc to przegladarki otwieraly sie najpierw w rozdzielczosci ktora byla zahardcodowana w mrcheckerze co wydluzalo troche testy"

**Comment by MalgorzataDzienia** [comment]
Development done and tested on my machine.  On Jenkins I will do tests when Jenkins works. 

Changes: 
1. new RuntimeParameter with name browserSize which expect values like  "800x600" - "widthxhight"
This parameter is optional, when not given then default value is set up.
2. Test class "RuntimeParametersTest" expanded for browserSize
3. Documentation in WIKI is open
