### ISSUE TITLE
[Selenium] Fix "Site" report generation

### ISSUE THREAD

**Issue by magdalenaBartkowiakJowsa** [devonfw/mrchecker#189]
@przwojtkow @tompalka @pawel-szczesny Could you please propose solution how to fix it?

**Comment by gabrielstar** [comment]
Are there any details on what is wrong?

**Comment by magdalenaBartkowiakJowsa** [comment]
Hej,
Gosia zna szczegóły, niestety jest na urlopie, chodzi o to że nie generuje się rapor, wydaje mi się że Patryk, Przemek, Tomek lub Paweł będą wiedzieli coś więcej.
Pozdrawiam,
Magda

**Comment by przwojtkow** [comment]
Without any logs we cannot diagnose the problem. Site is just an pluggin added to maven and it interpretes the units test execution results. When no tests were executed then no report will be generated.

**Comment by Fab-Bit** [comment]
I run with debug mode http://10.40.234.40:8080/job/MrChecker-SDLC/job/CI_mrchecker-selenium-module/106/consoleFull
and  here is an error 
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /usr/share/maven2
09:50:49 [DEBUG] Failed to decrypt password for server ossrh: org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException: /home/jenkins/.m2/settings-security.xml (No such file or directory)
09:50:49 org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException: /home/jenkins/.m2/settings-security.xml (No such file or directory)
