### ISSUE TITLE
Unable to upload file with NewRemoteWebDriver

### ISSUE THREAD

**Issue by rafalku** [devonfw/mrchecker#218]
When NewRemoteWebDriver is used, on attempt to set path for a file input field the following exception is thrown:
org.openqa.selenium.InvalidArgumentException: invalid argument: File not found

I think it's related to setting file detector in NewRemoteWebElement implementation. I've worked this problem around in the following way:
```
		if (getDriver() instanceof NewRemoteWebDriver) {
			((NewRemoteWebElement) input).setFileDetector(new LocalFileDetector());
		}
```

**Comment by arturbalcz** [comment]
I believe it's because LocalFileDetector should be seted to RemoteWebDriver after creating the object. 
Now in DriverManager class it looks like this: 
```
NewRemoteWebDriver newRemoteWebDriver = null; 
try {  
    newRemoteWebDriver = new NewRemoteWebDriver(new URL(SELENIUM_GRID_URL), capabilities);  
} catch (MalformedURLException e) {  
    e.printStackTrace();  
    System.out.println("Unable to find selenium grid URL: " + SELENIUM_GRID_URL);  
}  
return newRemoteWebDriver;
```  

Adding this statement after constructor call should solve the issue: 
`newRemoteWebDriver.setFileDetector(new LocalFileDetector());`
