### ISSUE TITLE
[Selenium] Code review created TC's - feature/horizontal_slider

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#22]
Pull Request to https://github.com/devonfw/devonfw-testing
https://bitbucket.org/capntc/selenium_workshop/branch/feature/horizontal_slider

**Comment by Pyskaczu** [comment]
Please review this item. It seems to be already implemented:
https://github.com/devonfw/devonfw-testing/blob/develop/example/src/main/java/com/capgemini/mrchecker/selenium/pages/projectY/HorizontalSliderPage.java

https://github.com/devonfw/devonfw-testing/blob/develop/example/src/test/java/com/capgemini/mrchecker/selenium/projectY/SliderTest.java
