### ISSUE TITLE
[Frame] MrChecker wiki is broken

### ISSUE THREAD

**Issue by baklarzej** [devonfw/mrchecker#221]
### Expected behavior
Selecting a chapter should lead to the corresponding wiki page.

### Actual behavior

All of the chapters redirect to link https://raw.githubusercontent.com/wiki/devonfw/mrchecker/Who-Is-MrChecker which contains just _404: Not Found._

### Steps to reproduce

1. Open https://github.com/devonfw/mrchecker/wiki and select some chapter on the right

**Comment by Pyskaczu** [comment]
@baklarzej  Hi, This issue has been fixed. Please verify.

**Comment by MalgorzataDzienia** [comment]
> @baklarzej Hi, This issue has been fixed. Please verify.

@Pyskaczu : images are still brocken. As example see: https://github.com/devonfw/mrchecker/wiki/Project-Organisation

**Comment by Pyskaczu** [comment]
@MalgorzataDzienia Bringing the images back needs more analysis.

**Comment by baklarzej** [comment]
Please reopen. Exact same situation happens again.
