### ISSUE TITLE
[Selenium] Code review created TC's - feature/ADORSZ-StatusCodes

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#24]
Pull Request to https://github.com/devonfw/devonfw-testing

https://bitbucket.org/capntc/selenium_workshop/branch/feature/ADORSZ-StatusCodes

**Comment by Pyskaczu** [comment]
Please review this item. It seems to be already implemented:
https://github.com/devonfw/devonfw-testing/blob/develop/example/src/main/java/com/capgemini/mrchecker/selenium/pages/projectY/StatusCodesCodePage.java

https://github.com/devonfw/devonfw-testing/blob/develop/example/src/test/java/com/capgemini/mrchecker/selenium/projectY/StatusCodeTest.java

**Comment by Wilczkiewicz** [comment]
Reviewed, no need to change anything.
