### ISSUE TITLE
differet colors for Bflogger

### ISSUE THREAD

**Issue by mcpabst** [devonfw/mrchecker#286]
For better reading of the log, it is better to have different colors.
maybe:
logInfo - black
logDebug - gray
logError - red

**Comment by KMariusz** [comment]
Console logs was made a bit more color.
![image](https://github.com/devonfw/mrchecker/assets/20811235/24eece59-f9e7-4ed4-b711-eb53cfa8ea82)

FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=blue, TRACE=black
