### ISSUE TITLE
[Selenium] Code review created TC's - feature/drag-and-drop

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#30]
Pull Request to https://github.com/devonfw/devonfw-testing

NOTE: Analyze this article   http://elementalselenium.com/tips/39-drag-and-drop  

https://bitbucket.org/capntc/selenium_workshop/branch/feature/drag-and-drop

**Comment by przwojtkow** [comment]
Example code:

Actions builder = new Actions(page.driver);
Action a = builder.clickAndHold(file).moveToElement(target).release(target).build();
a.perform();
