### ISSUE TITLE
[Selenium] Code review created TC's - feature/RedirectLink

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#35]
Pull Request to https://github.com/devonfw/devonfw-testing

https://bitbucket.org/capntc/selenium_workshop/branch/feature/RedirectLink

**Comment by WroMaciej** [comment]
Website which is redirect`s link http://the-internet.herokuapp.com/status_codes is blocked to all Capgemini users.
I`m proceeding the internal IT request to check possibility to unblock that site, but looks that it is not possible to set a global unblocker (without manual logging into that site).

**Comment by WroMaciej** [comment]
Website is finally unblocked by firewall.
