### ISSUE TITLE
[Maintenance] Run MTS tests locally

### ISSUE THREAD

**Issue by michalbabiarz** [devonfw/mrchecker#356]
Please run MTS locally from docker-compose file, run Selenium and API test for both JUnit and Cucumber.
Also prepare a short instruction how to run MTS locally.

**Comment by andrzejsamson** [comment]
MTS can be run locally via docker. API tests run successfully local. Selenium tests for JUnit and Cucumber had problems. The firefox browser where I run the tests had problems with: "Browsing context has been discarded" and "Failed to decode response from marionette". The second issue is that some elements were not found - maybe the code from the elements changed.

**Comment by andrzejsamson** [comment]
[Uploading myThaiStarReports.zip…]()

**Comment by andrzejsamson** [comment]
Short info how to run MTS locally:

1. Download Docker -> it can be done found [here:](https://hub.docker.com/editions/community/docker-ce-desktop-windows/)
2. Clone MTS repo from github -> https://github.com/devonfw/my-thai-star
3. Go to the folder where the repo is stored.
4. Open CLI in that location.
5. Run command -> docker-compose up
6. The first run takes a few minutes.
7. When the docker is running MTS is available on: localhost:8081/restaurant
8. To stop the docker file run in CLI -> docker-compose down

MTS is available only when docker is running. Access to the API is via localhost:8081/api

**Comment by Pyskaczu** [comment]
Hi @other019 is the instruction included on the Wiki already?
