### ISSUE TITLE
[Selenium] Code review created TC's - feature/ContextMenu

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#38]
Pull Request to https://github.com/devonfw/devonfw-testing

https://bitbucket.org/capntc/selenium_workshop/branch/feature/ContextMenu

**Comment by przwojtkow** [comment]
Connected with: #50

**Comment by WroMaciej** [comment]
It looks that tested page http://the-internet.herokuapp.com/context_menu is broken.
No context menu is available after right-click (Alert is shown immediately instead of after context menu option click). Till third party supplier fix that, we cannot test Context Menu.
