### ISSUE TITLE
[DevOps][WebAPI][Service Virtualization] Example REST  docker image

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#42]
1. This looks  promising:   https://github.com/jgontrum/spacy-api-docker   
2. Send request to our Arch community. Probably they have such example image
OR. 
3. We should use Devonfw -  Mai Tahi Start application. And this would be the best option. 

Acceptance criteria: 
* Docker compose starts REST API
* Docker compose, dockerfile are saved in devon-testing repo under /example folder
* Docker image is uploaded to https://cloud.docker.com/repository/docker/lucst/capntc  as lucst/mai-thai-start-api

**Comment by pawel-szczesny** [comment]
http://httpbin.org/ is dockerized right now -> [github](https://github.com/postmanlabs/httpbin)

**Comment by klaudia-nowak** [comment]
Closing, because issue is outdated
