### ISSUE TITLE
[DevOps][DB] Docker image with example SQL database with data [PART 1]

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#46]

**Comment by przwojtkow** [comment]
Main goal of this task is to create an dockerimage with MySQL database https://hub.docker.com/_/mysql.
Database inside should be empty. Testing data should be provided by PART 2.

Valid output:

1. Dockerfile with MySQL database. This file with all non-binaries dependencies should be placed somewhere inside repository.
2. Dockerimage based on dockerfile from point 1. should be tested (connect with db, execute simple query on systems tables).
3. To discuss: Image can be pushed to the docker hub under Capgemini, devonfw profile.
