### ISSUE TITLE
[Selenium] Add rightClick() method

### ISSUE THREAD

**Issue by przwojtkow** [devonfw/mrchecker#50]
Nice to have mouse right click function covered. Sample code to copy- paste in each situations where this functionality is needed.

**Comment by przwojtkow** [comment]
@lstefaniszyn test for new functionality is blocked - newest firefox driver is needed which is supported only for Selenium over v3.5.

**Comment by lstefaniszyn** [comment]
@przwojtkow :  please merge branch feature/upgradeSeleniumTo381  
this is upgrade to selenium 3.8.1

**Comment by przwojtkow** [comment]
#62

**Comment by gabrielstar** [comment]
@lstefaniszyn un @przwojtkow  - it looks this has already been implemented: 
![image](https://user-images.githubusercontent.com/38763186/61771823-0db1f200-adf1-11e9-953c-c6697af5016f.png)

Should we close this task ?
